os: linux
language: cpp
services:
  - docker

before_script:
  - mkdir -p build ci-tester coverage_report; chmod a+rwX build ci-tester coverage_report

script:
  - docker run --rm -v $(pwd)/ci-tester:/app -v $(pwd):/src triggerhappy/cppdev:latest bash
    -c "scripts/build.sh /app"
  - tar cJf ci-tester.tar.xz ci-tester
  - sudo rm -rf build/*

  - docker run --rm -v $(pwd)/coverage_report:/app -v $(pwd):/src triggerhappy/cppdev:latest
    bash -c "scripts/coverage_report.sh /app"
  - bash <(curl -s https://codecov.io/bash) -f coverage_report/coverage.json

  - PREVIOUS_TAG=$(git describe --abbrev=0 --tags `git rev-list --tags --skip=1 --max-count=1`)
  - STARTING_COMMIT=$(git log --pretty="%h" $PREVIOUS_TAG..HEAD | awk '/./{line=$0} END{print line}')
  - docker run -v `pwd`:/src --rm -i triggerhappy/auto-changelog:latest auto-changelog --starting-commit=$STARTING_COMMIT
  - cat CHANGELOG.md

deploy:
  draft: false
  release_notes_file: CHANGELOG.md
  tag_name: $TRAVIS_TAG
  cleanup: false
  edge: true
  provider: releases
  api_key:
    secure: b5g+dPDJZ0kvl0hs3X6fbs5cmuP/c/aBfuSU0Zgdq1zqZXWuRy2QaUiUGn1iyjPgrEDR0oWUJwiQJAITkiePJu18gPANAAYoVgC5GyzhGBDBWRlxF0suRYaEFIFN/kA9n9VfSuVbwnY/6whp4VMNe/Bu8M4gittGGysr+VUXIc00aaiAImY68/v8fXfc2t8qzJUn419q90sc9uADnFlwIvqtUY1KGl7tHmIvcKZUx/XeWpArao36RoSTuY7ncqwGnlX5e577daE4GidSTtp1skJd72wDe6W6NLWiMFDy/duyOXqj4VWL7CRg+dcGYE9Sc6T80Z/WFPqxtrIYRX5vCAJUfbR9nMbhxLTKVyP60LncdzE/Jmj7axcXCKvBXku/zyB2I0flaCpmbt++C1nT0KvMnEPgzWIoTEUbBQSgetXhziV0GyPp7ca/S9CjJZ3aTKAJt2ov59yMmIbivCkqLJjCCbnAstSg0JXl+JykzD3RT3WPAfJobhKrrTpkUnRIYRaPwHKMYnSVV/ekULvbY+aTo4BylxXfv9vwFy10iP03aOpwpXoswtZwdzabHB8HXarGTFz/+9zjBhNQHiVs/SDxKTAPXNOfSIQQS5gMvZ1ulyBblI7iZSundrbkYv2VAcrGPGexp+NbD0AYqgx9+KjkcnoBibU9hpOx4+Pu5zg=
  file: ci-tester.tar.xz
  on:
    tags: true
    repo: trigger-happy/ci-tester
