os: linux
language: cpp
services:
  - docker

before_script:
  - mkdir -p app coverage_report; chmod a+rwX app coverage_report

script:
  - docker run --rm -v $(pwd)/app:/app -v $(pwd):/src triggerhappy/cppdev:latest bash -c "scripts/build.sh /app"
  - tar cJf ci-tester.tar.xz app

  - docker run --rm -v $(pwd)/coverage_report:/app -v $(pwd):/src triggerhappy/cppdev:latest bash -c "scripts/coverage_report.sh /app"
  - bash <(curl -s https://codecov.io/bash) -f coverage_report/coverage.json
