sudo: required
language: cpp
services:
  - docker

before_install:
  - docker build . --target build-env -t $DOCKER_USERNAME/ci-tester:build-env

script:
  - mkdir -p app
  - docker run --rm -v $(pwd)/app:/app ci-tester:build-env bash -c "scripts/build.sh /app"
